spring:
  application:
    name: GraphQl-Sample
  graphql:
    graphiql:
      enabled: true
    #    websocket:
    #      path: /graphql
    schema:
      inspection:
        enabled: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: sample-service-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    properties:
      schema.registry.url: http://localhost:8081
      specific:
        avro:
          reader: true
      spring:
        deserializer:
          key:
            delegate:
              class: org.apache.kafka.common.serialization.StringDeserializer
          value:
            delegate:
              class: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      bootstrap-servers: localhost:9092
      client-id: sample-service-producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer


    template:
      default-topic: create-product

dgs:
  reload: true
  graphql:
    enable-entity-fetcher-custom-scalar-parsing: true
    spring:
      webmvc:
        asyncdispatch:
          enabled:
            debug: true

#app:
#  topic:
#    product-topic: sample-topic
